version: '3.9'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=SuperStronkPassword!"
    ports:
      - "1433:1433"
    networks:
      receptnetwork:
          aliases: 
          - sqlserver

  api:
    image: "recepati:latest"
    ports:
      - "8081:80"
      - "8082:443"
    environment:
      - "DB_LOCATION=localhost"
      - "DB_USERNAME=sa"
      - "DB_PASSWORD=SuperStronkPassword!"
    networks:
      receptnetwork:
        aliases:
          - apiserver
networks:
  receptnetwork: {}

