version: '3.3'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - "ACCEPT_EULA=Y"
      - "SA_PASSWORD=SuperStronkPassword!"
    ports:
      - "1433:1433"
    volumes:
      - /home/sql/data:/var/opt/mssql/data
      - /home/sql/log:/var/opt/mssql/log
      - /home/sql/secrets:/var/opt/mssql/secrets
    networks:
      receptnetwork:
          aliases: 
          - sqlserver

  api:
    image: "blackwinged/recepati:latest"
    ports:
      - "8081:80"
      - "8082:443"
    environment:
      - "DB_LOCATION=sqlserver"
      - "DB_USERNAME=sa"
      - "DB_PASSWORD=SuperStronkPassword!"
    networks:
      receptnetwork:
        aliases:
          - apiserver
  
  front:
    image: "blackwinged/recepati_front:latest"
    ports:
      - "8080:80"
    networks:
      receptnetwork:
        aliases:
          - frontend
networks:
  receptnetwork: {}

